version: "3.8"
services:
  db:
    container_name: batch-db
    image: "postgres:13.6-alpine"
    ports:
      - "5432:5432"
    volumes:
      - batch-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  batch-pg-data:
