spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    driverClassName: org.postgresql.Driver
    username: batch
    password: batch
    hikari:
      connection-timeout: 20000 # maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1           # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 20     # maximum pool size
      idle-timeout: 1000        # maximum idle time in milliseconds for a connection
      max-lifetime: 1000        # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true         # default auto-commit behavior.
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

file:
  input: coffee-list

thread:
  size: 10
